### ISSUE TITLE
"Read more" break table template

### ISSUE THREAD

**Issue by awerlang** [Dynalon/mdwiki#174]
When using preview syntax in a document, "...read more" is being rendered inside the table.

The issue can be seen here:
http://blog.werlangtecnologia.com.br/md/#!index.md#Heading

**Comment by rjsteinert** [comment]
What is this preview syntax feature?

**Comment by rjsteinert** [comment]
Hm. I can't find documentation on this gimmick but I see it works.

```
[preview:3](documentation.md)
```
