### ISSUE TITLE
Code fencing of unknown types hangs the browser

### ISSUE THREAD

**Issue by bartgrantham** [Dynalon/mdwiki#186]
Terrible bug.  Doing code fencing of an unknown syntax type will cause the browser to hang.  I experienced this twice, in Firefox with
\`\`\`openscad
...
\`\`\`

and in Chrome with

\`\`\`ini
...
\`\`\`

I have no reason to think that this isn't a general problem for any unknown syntax type and browser.

**Comment by Dynalon** [comment]
duplicate of #39
