### ISSUE TITLE
MDWiki throws an error when built from master

### ISSUE THREAD

**Issue by russellseymour** [Dynalon/mdwiki#194]
Hello,

I appreciate that 'master' is undergoing a lot of changes so this might be related. 

I wanted to update the prism languages to include 'PowerShell' so I cloned the project and tested to see if it would work with my current Wiki and unfortunately it did not.  The error I get in developer tools in Chrome is:

![image](https://cloud.githubusercontent.com/assets/791658/6229702/4067abe0-b6b1-11e4-9abd-bc42d85a61a3.png)

Is this a known problem?

Thanks for the great software, it is really helping with getting some documentation distributed.  I really appreciate the simplicity of putting a wiki together and have it rendered on the fly.

Russell

**Comment by Dynalon** [comment]
master may break at any time, use the stable branch instead
