### ISSUE TITLE
Can't build repo - typescript grunt task fails

### ISSUE THREAD

**Issue by chrisUsick** [Dynalon/mdwiki#202]
Running "typescript:base" (typescript) task
Verifying property typescript.base exists in config...OK
Files: js/ts/LinkRewriter.ts, js/ts/basic_skeleton.ts, js/ts/bootstrap.ts, js/ts/gimmickloader.ts, js/ts/gimmickparser.ts, js/ts/logger.ts, js/ts/main.ts, js/ts/markdown.ts, js/ts/navigationmodel.ts, js/ts/stage.ts, js/ts/template.ts, js/ts/theme.ts, js/ts/utils.ts, js/ts/wiki.ts -> ts_compiled/mdwiki_ts.js
Reading c:\Users\chris\p\mdwiki\node_modules\grunt-typescript\node_modules\typescript\bin\typescript.js...OK
Options: target="es5", basePath="/js/ts/", sourcemap=false, fullSourceMapPath=false, declaration=false
Reading c:/Users/chris/p/mdwiki/js/ts/LinkRewriter.ts...OK
Reading c:/Users/chris/p/mdwiki/typings/tsd.d.ts...OK
Reading c:/Users/chris/p/mdwiki/typings/jquery/jquery.d.ts...OK
Reading c:/Users/chris/p/mdwiki/js/ts/basic_skeleton.ts...OK
Reading c:/Users/chris/p/mdwiki/js/ts/bootstrap.ts...OK
Reading c:/Users/chris/p/mdwiki/js/ts/utils.ts...OK
Reading c:/Users/chris/p/mdwiki/js/ts/template.ts...OK
Reading c:/Users/chris/p/mdwiki/js/ts/gimmickloader.ts...OK
Reading c:/Users/chris/p/mdwiki/js/ts/gimmickparser.ts...OK
Reading c:/Users/chris/p/mdwiki/js/ts/logger.ts...OK
Reading c:/Users/chris/p/mdwiki/js/ts/main.ts...OK
Reading c:/Users/chris/p/mdwiki/js/ts/markdown.ts...OK
Reading c:/Users/chris/p/mdwiki/js/ts/navigationmodel.ts...OK
Reading c:/Users/chris/p/mdwiki/js/ts/stage.ts...OK
Reading c:/Users/chris/p/mdwiki/js/ts/theme.ts...OK
Reading c:/Users/chris/p/mdwiki/js/ts/wiki.ts...OK
Reading c:/Users/chris/p/mdwiki/node_modules/grunt-typescript/node_modules/typescript/bin/lib.d.ts...OK
Warning: Task "typescript:base" failed. Use --force to continue.

Aborted due to warnings.

**Comment by Dynalon** [comment]
`master` is under development may break at any time. Use the stable 0.6.x branch for custom building.

**Comment by Dynalon** [comment]
However, even for master we have a travis-ci auto build, and the build on the CI system is passing: https://travis-ci.org/Dynalon/mdwiki

**Comment by chrisUsick** [comment]
Okay, thanks. It must be a bug with my local machine. Possibly a windows problem.
