### ISSUE TITLE
Why embed marked when it has a bower package?

### ISSUE THREAD

**Issue by MetaMemoryT** [Dynalon/mdwiki#203]
https://github.com/Dynalon/mdwiki/blob/master/js/marked.js

Is their special modifications?

https://github.com/chjj/marked

**Comment by Dynalon** [comment]
There are minor modifications to it: https://github.com/Dynalon/mdwiki/commits/master/js/marked.js

For futures MDwiki releases, I've been looking into [commonmark](http://commonmark.org) but the current JS implementation has a too large footprint (140kb unpacked/unzipped).
