### ISSUE TITLE
doesn't work for me either

### ISSUE THREAD

**Issue by rickdog** [Dynalon/mdwiki#212]
I also get a blank page.  I downloaded mdwiki-0.6.2.zip, it contains these files only:

-rw-r--r--    1 rickdog  Administ    35147 May 23  2014 GPLv3.txt
-rw-r--r--    1 rickdog  Administ     2389 May 23  2014 LICENSE.txt
-rw-r--r--    1 rickdog  Administ       79 May 23  2014 README.md
-rw-r--r--    1 rickdog  Administ   408885 May 23  2014 mdwiki-debug.html
-rw-r--r--    1 rickdog  Administ    85028 May 23  2014 mdwiki-slim.html
-rw-r--r--    1 rickdog  Administ   339025 Apr 13 21:39 mdwiki.html

...
load mdwiki.html from the zip file in browser:

GET 
http://localhost:8000/mdwiki.html#!index.md [HTTP/1.0 200 OK 4ms]
GET 
http://localhost:8000/navigation.md [HTTP/1.0 404 File not found 2ms]
GET 
http://localhost:8000/config.json [HTTP/1.0 404 File not found 2ms]
GET 
http://localhost:8000/index.md [HTTP/1.0 404 File not found 2ms]
"[ERROR] unable to retrieve config.json: error" mdwiki.html:198:13673
"[FATAL] Could not get index.md"File not found 2ms]
"[FATAL] Could not get config.json"File not found 2ms]

The .zip is missing 3 files: navigation.md, config.json, index.md.
Found documentation for navigation and index.md at http://dynalon.github.io/mdwiki/#!quickstart.md.
Where's the documentation for config.json?

It would be very useful for people doing initial setups to have these three files included in the .zip so they're not looking at a blank screen while scratching their heads.  Also a readme for these three files pointing to documentation for setting them up.

**Comment by cportet** [comment]
@rickdog you should have read the mdwiki website, all is clearly explained here : http://dynalon.github.io/mdwiki/#!index.md

You just have to create your index.md file by yourself and follow all the tiny documentation !

**Comment by Dynalon** [comment]
Yes, seems to me like the `index.md` is missing. The ´config.json` and `navigation.md` are optional, but `index.md` is required (at least when you provide an `#!index.md` hashbang). Feel free to reopen if this does not solve your problem.

**Comment by rickdog** [comment]
The ´config.json and navigation.md were not optional for me, I got a blank screen until I went out to some of the example sites and installed theirs, then it worked.  This is on a WAMP stack.
