### ISSUE TITLE
Offline support in Chrome

### ISSUE THREAD

**Issue by talek** [Dynalon/mdwiki#218]
Hi,

I have started Chrome with `--allow-access-from-files` but it still doesn't work:

![chrome-mdwiki](https://cloud.githubusercontent.com/assets/190845/7386193/b4f1ccc2-ee59-11e4-99f6-545968ab87a7.png)
![chrome-version](https://cloud.githubusercontent.com/assets/190845/7386195/b7f38b9a-ee59-11e4-8036-8dcd47f17e95.png)

Any ideas?

Thanks!

**Comment by AndreaGiardini** [comment]
The option you are using is not correct. 
You should use `google-chrome --allow-file-access-from-files` . 

It works in this way, cheers

**Comment by Dynalon** [comment]
If the parameter name was changed in chrome, the documentation might need updating.

**Comment by AndreaGiardini** [comment]
The documentation is correct: http://dynalon.github.io/mdwiki/#!faq.md

**Comment by talek** [comment]
Thanks guys! It's working!
