### ISSUE TITLE
Cookie law JavaScript

### ISSUE THREAD

**Issue by spike1234** [Dynalon/mdwiki#220]
Hi!

I'm trying to add some JavaScript to comply to the *EU Cookie Law*.
I'm using the service offered by http://iubenda.com and I have to add some `<SCRIPT>` tag in my page.

I've added in `navigation.md` (where I already have other scripts), but MDWiki fails to load.

Then I've tried modifying the `mdwiki.html`: the site loads, but nothing from this script appears.

can someone help me?

=)

**Comment by spike1234** [comment]
I've tried with this script: http://www.cookiechoices.org but the problem persists: where can I insert this JavaScript?

**Comment by Dynalon** [comment]
Short anwser: You can't just include any script tag into MDwiki. Most external script run when the website is ready (like some Jquery `$(document).ready()`) - but MDwiki at this point is not yet a valid website, because the MDwiki scripts themselves run.

Btw., MDwiki does **not** set any cookies.

**Comment by spike1234** [comment]
First of all, thanks for your reply!
I know that MDwiki doesn't set cookies, but it seems I'm required by law to alert viewers of my site about third party plugins (Google Maps, for example).

Just another question: what if I "embedd" (like minify&copy&paste into mdwiki.html) the external JScript file? Could it work?
