### ISSUE TITLE
force theme

### ISSUE THREAD

**Issue by benavern** [Dynalon/mdwiki#221]
Hello,
I looked for that and think it is possible but didn't find the way to do it.

**Is it possible to force a particular theme?**

By default this is the bootstrap theme and the only way I found to change the theme is by adding the "change theme" gimmick.

I would like to force the `cerulean` theme and can't figure out how to do that.

I tried by adding 

``` json
   "theme": "cerulean"
```

in the config.json file but that didn't work.

Thank's in advance

**Comment by spike1234** [comment]
I hope I understood your question!

try looking here:

http://dynalon.github.io/mdwiki/#!customizing.md#Theme_chooser

**Comment by benavern** [comment]
OOOOh, I'm sorry 

I missed this, I just saw the `theme chooser` but not the `selecting a theme` part http://dynalon.github.io/mdwiki/#!customizing.md#Selecting_a_theme

It worked perfectly.
Thank you and sorry again!

**Comment by gitmithy** [comment]
i want to know how to add secondary menu in navigation.md .thank you！

**Comment by xephon2** [comment]
@benavern Could you please close this issue?
