### ISSUE TITLE
Page hangs when I change language for syntax highlighting

### ISSUE THREAD

**Issue by neman** [Dynalon/mdwiki#224]
You can reproduce this bug with mdwiki example on page http://dynalon.github.io/mdwiki/#!quickstart.md.

I cloned the example from github repo https://github.com/Dynalon/mdwiki/tree/gh-pages
I changed language from javascript to csharp and page hangs.

`javascript`
```javascript
var hello = function () {
    // say hello
    alert('Hello world!');
}
```

`csharp`
```csharp
var hello = function () {
    // say hello
    alert('Hello world!');
}
```

**Comment by Dynalon** [comment]
duplicate of #39
