### ISSUE TITLE
PDF files in a "tmp" directory label:question

### ISSUE THREAD

**Issue by Gaoura** [Dynalon/mdwiki#228]
Hi,
First of all, thank you for your awesome mdwiki :3
I was wandering randomly in my directories and just found on my partition E: the "tmp" directory which contains some of the files in my wiki as PDF. It's an interesting functionality but how can I control it ? 
I mean I have no idea how these files popped (2 days in a row, at 5:18/19 and 6:18/19 AM) but I would like to do it on purpose. I would like to control the quality too (the text is a bit dirty/pixelated except for headings) if it's possible.

**Comment by Dynalon** [comment]
I don't know how you got your PDF files there but this is nothing related to mdwiki and nothing that is technically possible from a javascript application / website.
