### ISSUE TITLE
Still cannot see gist

### ISSUE THREAD

**Issue by Wilbeibi** [Dynalon/mdwiki#237]
Although I found [https://github.com/Dynalon/mdwiki/pull/97](https://github.com/Dynalon/mdwiki/pull/97).
But the problem still exist. Only the pure numerical gist works fine.

Like my [https://gist.github.com/Wilbeibi/7d4e92d6da25195cb1ab](https://gist.github.com/Wilbeibi/7d4e92d6da25195cb1ab) with `[gimmick:gist](7d4e92d6da25195cb1ab)`.

Thanks

**Comment by Dynalon** [comment]
duplicate of #150
