### ISSUE TITLE
Latest production version doesn't seem to work

### ISSUE THREAD

**Issue by axefrog** [Dynalon/mdwiki#241]
I just tried the latest version; both the debug and the production version. The debug version seems to work fine, but the minified version throws this error:

```
Uncaught TypeError: a.initMDwiki is not a function
```

I'm using Chrome 47 (beta channel), but I get the same issue in Firefox 41.0.2

**Comment by Dynalon** [comment]
`master` branch is broken (and can be at any time), try the `stable-0.6.x` branch (which is the current stable/production version)

**Comment by axefrog** [comment]
Ok, thanks.
