### ISSUE TITLE
Character Encoding

### ISSUE THREAD

**Issue by Zottelchen** [Dynalon/mdwiki#242]
If you write characters like: ä ü ö ß 
they don't get encoded properly. They show only �

here is a (german) site which lists a lot of typical characters which are used:
https://wiki.selfhtml.org/wiki/Referenz:HTML/Zeichenreferenz#HTML-eigene_Zeichen

Might want to consider adding these.

**Comment by Dynalon** [comment]
I'd rather guess that the source markdown file is not in the `UTF-8` encoding. Try saving with an editor that supports different encodings and chose UTF-8 and see if that fixes the problem.

**Comment by Zottelchen** [comment]
Oh, yeah, I am sorry. Even though I use Notepad++ I didn't think of that.
