### ISSUE TITLE
file:///C:/Users/dsf/Desktop/doc/index.html#!index.md can't load markdown file

### ISSUE THREAD

**Issue by djfly** [Dynalon/mdwiki#246]
file:///C:/Users/dsf/Desktop/doc/index.html#!index.md can't load markdown file
must use http://www.xxx.com/doc/#!index.md to work
This is a path problem!

**Comment by theidecke** [comment]
I second that. Exact same problem here.

**Comment by Dynalon** [comment]
This is most likely because you are using a browser that does not correctly support loading from `file://` urls. See the FAQ entry at http://dynalon.github.io/mdwiki/#!faq.md#Q:_Can_I_open_mdwiki.html_in_my_browser_from_the_menu_or_by_specifying_via_a_file://_URL?
