### ISSUE TITLE
Dockerfile for quick serving

### ISSUE THREAD

**Issue by vwbusguy** [Dynalon/mdwiki#253]
If it's of interest to include in your project, we've created a basic Dockerfile for quickly deploying an mdwiki.  It uses python's SimpleHTTPServer and a simple volume mount for including the md files on run.

It extracts the current release by zip.

```
FROM python:2.7

RUN mkdir -p /usr/src/mdwiki
RUN apt-get update && apt-get install -yq unzip && wget https://github.com/Dynalon/mdwiki/releases/download/0.6.2/mdwiki-0.6.2.zip && unzip mdwiki-0.6.2.zip && cp mdwiki-0.6.2/* /usr/src/mdwiki

VOLUME /md-app
WORKDIR /md-app

EXPOSE 80

CMD cp -f /usr/src/mdwiki/mdwiki.html /md-app/index.html && python -m SimpleHTTPServer 80
```

**Comment by vwbusguy** [comment]
A slight update with parameterized release version:

```
FROM python:2.7

ENV MDWREL 0.6.2

RUN mkdir -p /usr/src/mdwiki
RUN apt-get update && apt-get install -yq unzip && wget https://github.com/Dynalon/mdwiki/releases/download/$MDWREL/mdwiki-$MDWREL.zip && unzip mdwiki-$MDWREL.zip && cp mdwiki-$MDWREL/* /usr/src/mdwiki

VOLUME /md-app
WORKDIR /md-app

EXPOSE 80

CMD cp -f /usr/src/mdwiki/mdwiki.html /md-app/index.html && python -m SimpleHTTPServer 80
```

**Comment by vwbusguy** [comment]
As a further explanation, on image creation, it grabs the release zip and unzips it into a mdwiki source folder.  (It also installs unzip - if a tarball were also available, this could be skipped.)

On container run, it copies over the mdwiki.html into the /md-app volume and serves it with a simple Python http server.  

There are several things that could be done instead, such as adding routing for the mdwiki.html so it doesn't need to be in the app folder at all or checking out a git repo by env - this is rather a barebones lightweight and simple startup, which seems to better fit the intent of the project.  There's no apache, nginx, etc.  Just -v the path to the md's and that's it.

**Comment by Dynalon** [comment]
I have mixed feelings towards Docker and am not using it actively. Am also not sure if this should go into mainline mdwiki, but maybe a tiny github repo with the Dockerfile and a README.md to make fellow mdwiki googlers happy to find it? Closing this as it is not a real issue (it would never be closed), but feel free to post any further links to the dockerfile here so others can benefit of it.

**Comment by vwbusguy** [comment]
Here's a link to the DockerHub repo: https://hub.docker.com/r/claremontmckenna/mdwiki/

**Comment by vwbusguy** [comment]
Also now on GitHub as well: https://github.com/claremontmckennacollege/docker-mdwiki
