### ISSUE TITLE
Over a year without a stable version

### ISSUE THREAD

**Issue by vinipsmaker** [Dynalon/mdwiki#258]
Hi guys, lots of commits popped on `master` branch, but no tagged release has been made. Which commit seems "stable" for me to grab?

**Comment by bartgrantham** [comment]
+1!  I **love** mdwiki, however there are some minor but very irritating bugs that 0.8 will probably fix.  Is there any way we can help push things forward?  What bugs/issues are blocking a 0.8 release?

**Comment by Dynalon** [comment]
Current master is almost a complete rewrite, and lots of things still need to be done. Fixing bugs should go into the 0.6.x branch (PRs welcome).
