### ISSUE TITLE
Current master is broken

### ISSUE THREAD

**Issue by bartgrantham** [Dynalon/mdwiki#259]
@Dynalon, you're probably away of this but building a clean version from master right now is broken.  On the debug version I get "TypeError: handler is null"/"Cannot read property 'loadStage' of null" on Firefox/Chrome.  The error is on line 17690 here:

```
17688                parser.linkReferences.forEach(function (ref) {
17689                    var handler = _this.selectHandler('link', ref.trigger);
17690                    _this.stages.getStage(handler.loadStage).subscribe(function (done) {
17691                        handler.callback(ref, done);
17692                    });
17693                });
```

The non-debug version the same error with a different variable name (`c` instead of `handler`), so it's probably the same.

**Comment by Dynalon** [comment]
`master` branch can be broken at any time, this is not a real bug
