### ISSUE TITLE
Sidebar not showing

### ISSUE THREAD

**Issue by ChristianAE** [Dynalon/mdwiki#268]
I have a site in my Wiki containing several headings. I placed a "config.json" file next to the mdwiki.html with the following content:

`{
    "useSideMenu": true
}
`
I expected a side menu to show up and have a link to the headings. This is not the case. Do I have to use a special kind of syntax to make the side menu aware of the headings?

Here my wiki .md file:

# master
**Name: master**

The *master* branch is the main branch. It's tip (HEAD) always points to a productive ready state.
# develop
**Name: develop**

The *develop* branch exists parallel to master. It contains the features for the next release. This would be the branch nightly builds are based on.
# feature
**Name: feature-[Bug-No][-description]**

**Comment by Dynalon** [comment]
the sideBar is composed of entry of SECOND LEVEL heading. Make sure you have second level headings (prefixed for example with `##`) in your markdown code. The sidebar won't show up if there is only one or no second level headings.

**Comment by ChristianAE** [comment]
Works. Thanks.
