### ISSUE TITLE
Why the restrictive license?

### ISSUE THREAD

**Issue by lbmn** [Dynalon/mdwiki#275]
Why the restrictive (A)GPLv3 license?  This is very unusual for the NodeJS ecosystem, which strongly perfers the perfect MIT license.  The statist anti-market ideology that was behind the GPL fad has only hurt the Free Software movement, and thankfully it is now in decline.

For [pacifist philosophical reasons](http://forum.freestateproject.org/index.php?topic=19771.0), I would never use anything that came with legal threats backed by force.  This position is increasingly common, especially for Node developers.  Just one example, [quoting a top node module dev](https://qnalist.com/questions/5523655/preferred-license-for-node-modules):

> I have zero dependencies on GPL modules for that reason and won't use any npm modules that are under the GPL licence. If you like collaboration or want people to use your code you should licence it as MIT, because it's virtually the community standard. (Meteor released with GPL a while back and was hitting back by the community and changed to MIT)

You can Google for "copyleft harmful", "GPL sucks", "GPL hurts free software", etc to find a lot more arguments from people of many different philosophical backgrounds.  You are alienating a significant and **growing** fraction of your potential users and contributors, many of whom have switched to NodeJS exclusively due to licensing!

See [copyfree.org/standard/licenses](http://copyfree.org/standard/licenses) for a large selection of licenses that are **genuine** Free Software.

No disrespect intended.  I hope you won't respond with hostility.  Obviously you can do whatever the heck you want.  Have a nice day.

**Comment by Dynalon** [comment]
1. MDwiki is not a NodeJS product; it does not run on NodeJS but in the Browser.
2. MDwiki is not a NodeJS **module** or **library** targeted at developers, but a finished, usable **product** targeted at endusers. While MIT is common for **libraries**, the GPL always has been a better choice for usable final products.
3. I don't like the idea of someone taking MDwiki, adding 1% of code and sells this product using 99% of my work. Thats why I use (A)GPL.
4. Note that MDwiki 0.6.x is still GPL licensed, only the master branch is AGPL.
