### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Sinderella** [Dynalon/mdwiki#280]
There's an additional semicolon appears on the navigation bar. I have zero knowledge on this thing, but it doesn't look right for me.

Screenshot: http://i.imgur.com/LTKVNJd.png

https://github.com/Dynalon/mdwiki/blob/2880fcfaf1efe97cad79d8d837dcd87524f8790f/templates/navigation/navbar.html#L15

**Comment by Dynalon** [comment]
master branch is currently broken, i am aware of this

**Comment by Dynalon** [comment]
Use the `0.6.x`branch for stable builds
