### ISSUE TITLE
navigation.md generator

### ISSUE THREAD

**Issue by yanako** [Dynalon/mdwiki#286]
MDwiki is very interesting, but I got tired of writing navigation.md. So I tried to make navigation.md generator script.
[mkmdnav.txt](https://github.com/Dynalon/mdwiki/files/360565/mkmdnav.txt)

I do not know how to contribute on GitHub because I  joined to GitHub only now.

**Comment by sa7mon** [comment]
@yanako The feature you're looking for is a "Pull Request". [Here's the GitHub page on how to do that.](https://help.github.com/articles/creating-a-pull-request/)
