### ISSUE TITLE
SEO is essential

### ISSUE THREAD

**Issue by Zhangzijing** [Dynalon/mdwiki#287]
I think every page should have a own title.
It's friendly to user and search engine.
![win title](https://cloud.githubusercontent.com/assets/15173855/17221333/fed59f1a-5525-11e6-94c1-d64e390392e5.jpg)

**Comment by Dynalon** [comment]
Due to the technical nature of MDwiki (being 100% run on the client) SEO is not possible. If you need SEO, you should look for another project.

**Comment by Polisurgist** [comment]
Not necessarily arguing that this needs to be reopened, but the vast majority of good SEO practices can/should be implemented entirely on the client side.

It's probably still more of a milestone than an issue, and probably something that would be better added via a pull request from someone who specializes in SEO, but it's doable.
