### ISSUE TITLE
Idea: Replace gimmicks with web components?

### ISSUE THREAD

**Issue by rjsteinert** [Dynalon/mdwiki#292]
Gimmicks are like the Markdown version of Web Components. While that is kind of cool, this project could manage less code if it made available Web Components using something like Polymer. Users would then have a lot more options because there are a [ton of available web components](https://customelements.io/) out there. Something like the Google Map gimmick could be replaced by the `<google-map>` Web Component (https://elements.polymer-project.org/elements/google-map).

I'm suggesting this because I'm considering making some mdwiki gimmicks, but I'd rather create Web Components for portability reasons. @Dynalon I'm wondering what your thoughts on this, if you have thought about it, the pros and cons.

**Comment by jcmendez** [comment]
+1

**Comment by jerik** [comment]
OT: I want to wirte a gimmick / script as well but struggle to find documentation how to do it. Any tips, suggestions where I can dig in?

**Comment by Dynalon** [comment]
The thing is with gimmicks that they may manipulate other content (especially content created by other gimmicks). As Webcomponents use an isolated shadow DOM, i don't think this is a good fit. Inlining Webcomponents however, would be a nice feature.
