### ISSUE TITLE
Need third party resource at first startup

### ISSUE THREAD

**Issue by radiumwu** [Dynalon/mdwiki#296]
I found that when a pc ran mdwiki at first startup without internet, pages could not be rendered normally.
Then I connected the internet, the problem gone.
It seems that mdwiki depends on some third party resources, like google.

May be this is not a issue, afterall network is everywhere, pcs and phones always online. 
I just wonder is it necessary to contain all the resources in the project?
Or is there a custom way, easy to configure the soft? 

Regards

**Comment by biank88** [comment]
![mdwiki-issue-cdn-libs](https://cloud.githubusercontent.com/assets/1591429/24316028/3c070b2c-10eb-11e7-86c9-3901f7d11fc8.png)

I'm also facing the same problem... the minified mdwiki tries to fetch some cdn repos.

**Comment by Dynalon** [comment]
This should only happen if you set a non-default theme (or the user has seleted one via bootstrap theme). For the fat (non-slim) build, i did not include every possible bootswatch theme as this would increase the filesize heavily.
