### ISSUE TITLE
# Heading <a name="withanchor"></a> causes page rendering exception

### ISSUE THREAD

**Issue by blueacorn** [Dynalon/mdwiki#297]
Classic Markdown does not include an internal anchor syntax.

Users, therefore have often used syntax:

```
  ## 4. Section 4<a name="section4"></a>

  ### 4.11 Tailoring Process <a name="tailoring"></a>
```

MDWiki v0.62 throws exception and does not render page when this syntax encountered:
![image](https://cloud.githubusercontent.com/assets/2761886/19604116/b9d86714-9768-11e6-9162-5a7b3eb8fe3d.png)

**Comment by Dynalon** [comment]
inline html is only allowed in separater paragraphs in markdown, AFAIK.
