### ISSUE TITLE
documentation how to write gimmicks or modules?

### ISSUE THREAD

**Issue by jerik** [Dynalon/mdwiki#299]
I want to integrate a search feature. A smoketest ist running, but I think the right way is to integrate it as a gimmick/module. Unfortunatly I do not know how to do this. Is there somewhere documentation or examples where I can dig in to get the knowledge? 

cheers -- jerik

**Comment by Dynalon** [comment]
unfortunately, there is only the source as an example (look in the `0.6.x` code branch, not `master`)
