### ISSUE TITLE
how about new release/tag/dist

### ISSUE THREAD

**Issue by dkebler** [Dynalon/mdwiki#306]
bunch of commits since the last release almost 3 years ago.
I tried compiling from the latest commit but it fails to render index.md.
Several packages are very deprecated which might be the issue.  

Is this project "dead"?  I can't find a functional fork that will compile. 

Great Project.  Wish it would stay current (at least compile successfully) even if none of the issues are resolved.

I've had this repo for awhile and it still works with the last release now 3 years ago. 
It seems time to update the code to the latest commits.
https://github.com/dkebler/mdwiki-kickstart-template

**Comment by Dynalon** [comment]
The current `master` is broken, the `0.6.x` git branch is the place for stable sources.
