### ISSUE TITLE
the browser tab always shows "MDwiki"

### ISSUE THREAD

**Issue by ballII** [Dynalon/mdwiki#312]
Can the tab show my website's brand name instead of "MDwiki"?

**Comment by pursellm** [comment]
You can change this by using a config.json file in your web root directory.  Just create a file called config.json in a text editor with the following content:

{
    "useSideMenu": true,
    "lineBreaks": "original",
    "additionalFooterText": "",
    "anchorCharacter": "&#x2693;",
    "title": "My Website"
}

**Comment by ballII** [comment]
Thank you, pursellm. Can it also show the title of the submenu page being navigated, like "My Website: Contact"?

**Comment by Dynalon** [comment]
Closing this as solved (submenu titles are not yet possible)
