### ISSUE TITLE
中文文件名.md 的打开后显示空白

### ISSUE THREAD

**Issue by masterwrw** [Dynalon/mdwiki#314]
文件内容是同样的，test.md 可以正常打开， 测试.md 就不行，文件是 UTF8 编码

**Comment by hortune** [comment]
正常而言檔名最好別用非英文。

**Comment by radiumwu** [comment]
如你所说，我这里很多文件都是以中文命名且为 UTF-8 编码，都是可以打开的。环境是 win10 及其 IIS。

**Comment by masterwrw** [comment]
win7下的中文文件名默认是 GBK 编码的
