### ISSUE TITLE
MDwiki v0.7.0 blank page

### ISSUE THREAD

**Issue by biank88** [Dynalon/mdwiki#317]
I've just tried to build MDwiki `v0.7.0 master`, unfortunately I always get a blank page with both the minified and debug build.
The test is performed by replacing a **working copy** of mdwiki `v0.6.2`.
Is there something I'm missing with v0.7.x?

**Comment by Dynalon** [comment]
`master` is broken (and may be anytime), use the `0.6.x` for current stable branch.

**Comment by xuwuqiang** [comment]
copy the file 'mdwiki.html'  from release mdwiki-0.6.2.zip 
then replace dist/mdwiki.html.
