### ISSUE TITLE
Enhancement Request: Automatically generate a list of incoming links for each page

### ISSUE THREAD

**Issue by GregEisenberg** [Dynalon/mdwiki#320]
Enhancement Request: In several Wikis I have created in the past, we have had a list of "incoming links" automatically generated for each page which helped for a few things

  1. automatically providing a back link to where you may have come from
  2. automatic navigation to related topics 
  3. a way to help identify pages which are no longer important (i.e. there are no incoming links to it) 
  4. a way to help prevent content from being repeated. Once we had incoming links in place - people were more willing to link the content on an existing page rather than repeat the content. (may have been a byproduct of several of the above advantages and more familiarity with good Wiki practices) 

Have you considered creating an "incoming links" section? 

Thanks
Greg

**Comment by bartgrantham** [comment]
This request doesn't make much sense, given how mdwiki works.  mdwiki is completely static, no databases, almost no configuration.  The first one (a "back" link) could be done in javascript, but two and three are impossible.

**Comment by Dynalon** [comment]
Agreed, due to the technial nature of mdwiki, this is not possible.

**Comment by GregEisenberg** [comment]
Okay. I realized as I was posting the request that this may be an implementation limitation due to the way MDWiki is built. Might be possible with an optional process which periodically walks the tree of possible pages generating the incoming links for each page.. but that would be a layer on top. Thanks for considering it.
