### ISSUE TITLE
"Page not found" in Chrome

### ISSUE THREAD

**Issue by mmartinortiz** [Dynalon/mdwiki#324]
When I open the `index.html` using Chrome, I get a "Page not found". I've tried with the official "last release" and compiling the `0.6.x` branch.

Here is the log output:

```
favicon.png Failed to load resource: net::ERR_FILE_NOT_FOUND
index.html:105 XMLHttpRequest cannot load file:///Users/manuel/my%20wiki/navigation.md. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
send @ index.html:105
index.html:105 XMLHttpRequest cannot load file:///Users/manuel/my%20wiki/config.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
send @ index.html:105
index.html:105 XMLHttpRequest cannot load file:///Users/manuel/my%20wiki/index.md. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
send @ index.html:105
index.html:198 [ERROR] unable to retrieve config.json: error
index.html:198 [WARN] Could not get ./index.md
index.html:105 XMLHttpRequest cannot load file:///Users/manuel/my%20wiki/404.md. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
send @ index.html:105
index.html:198 [FATAL] Could not get a user defined 404.md
favicon.png Failed to load resource: net::ERR_FILE_NOT_FOUND
```
macOS Sierra 10.12.4
Chrome 58.0.3029.81 (64-bit)
With Firefox 53.0 (64-bit) is working perfectly

**Comment by JosephTech** [comment]
I fixed this issue by configuring my web site to allow Markdown MIME type: text/markdown for .md extension

**Comment by chtixof** [comment]
Hello. The demo link in  http://dynalon.github.io/mdwiki/#!tutorials/drive.md does not work. Is "hosting" in G. Drive still possible?
Thanks for sharing your devs and this simple Ajax displayer. Keep it simple.

**Comment by Paraidomat** [comment]
@chtixof This seems to be a different issue, since @mmartinortiz seems to hosts the files in his local file system, but Chrome won't let him do it. It has nothing to do with the example and the G-Drive hosting.

**Comment by chtixof** [comment]
You are right @Paraidomat 
Following your remark, I opened https://github.com/Dynalon/mdwiki/issues/356

**Comment by Dynalon** [comment]
Using local filesystem in Chrome does not work out of the box, you have to start chrome with a special commandline flag (see the FAQ of MDwiki).
