### ISSUE TITLE
is this project still active?

### ISSUE THREAD

**Issue by jlozadad** [Dynalon/mdwiki#331]
I been interested in deploying this but, it looks like PR are stuck and tons of issues from a lot time are still open.

**Comment by bartgrantham** [comment]
Official word is that development is a non-master branch, but I forget which one.  It certainly seems like development has stalled.  I would fork but I can't get the build to work, and it seems like a pretty complex build even if it did.

I really like the project and it's **amazingly** useful, so I'm contemplating doing my own implementation with an eye toward keeping it a little simpler (using CommonMark for markdown, avoiding a complex build process, etc.).  But I have too little time to code as it is and I have much more important things to work on.  :(

**Comment by jlozadad** [comment]
I understand. I thought about forking but, I barely have any js experience so it would be a waste of time on my end. I was really looking into this project because I was using hugo and similar static pages but, it seem to be more complicated and need a lot of changes. This project seemed like a good solution, easy template and straight up to use in gitlab pages.

**Comment by guategeek** [comment]
I wish this was in active development, there a lots of little tweaks that would make it an even better solution. I love MDWiki I use it for all of my personal project wikis, so nice to just write markdown files and organize them however I like, and store all of it in a git repository. If anyone goes ahead and forks it let me know!

**Comment by jlozadad** [comment]
@guategeek I'm thinking of forking it but, I have small experience in the required programming skills for this.

**Comment by nmaro** [comment]
What a pity coming back after a few years and see this dead. Used it a ton during my studies.

**Comment by Dynalon** [comment]
I am closing this as this is not really a bug that can be fixed by a commit or such.
