### ISSUE TITLE
Release notes for 0.6.3?

### ISSUE THREAD

**Issue by dskrvk** [Dynalon/mdwiki#352]
Been a while since the last release, and the list of commits is long. What are the main changes in 0.6.3? Also, there's no compiled version for 0.6.3 on the releases page (and the latest available on https://dynalon.github.io/mdwiki/#!download.md is 0.5.8).

**Comment by Dynalon** [comment]
0.6.3 was a broken release which I assembled from several PRs, but after release noticed is completely broken. I thus pulled it. L
