### ISSUE TITLE
Display text that is underlined and not a link.

### ISSUE THREAD

**Issue by dcvice1967** [Dynalon/mdwiki#354]
I have tried several of the combinations of formatting used in other markdown tools to display underlined text but none seem to work with mdwiki. The link below shows how other tools provide this feature. Is this possible with mdwiki?

https://www.wikimatrix.org/syntax.php?i=25

**Comment by Dynalon** [comment]
No, currently not supported. Highlighting in Markdown is done by using single- or double asterisk: * or ** which will render slanted or bold, but never underlined
