### ISSUE TITLE
Dead link and "hosting" in Google Drive

### ISSUE THREAD

**Issue by chtixof** [Dynalon/mdwiki#356]
The link in the "Demo Website section of http://dynalon.github.io/mdwiki/#!tutorials/drive.md does not work.
So, the questions are:
- Is  "hosting" in Google Drive still possible?
- What other solutions do you suggest for a free private mdwiki?

**Comment by Dynalon** [comment]
You can use git hosting providers to host your wiki, the mdwiki.info website is hosted for free on a GitHub account using GitHub Pages: https://pages.github.com/

BitBucket does also work, AFAIK.
