### ISSUE TITLE
IE 7-8 Compatibility Issues

### ISSUE THREAD

**Issue by utensil** [Dynalon/mdwiki#90]
This issue is similar to a portion of #18 , but I intend to focus on IE 7-8, because MDWiki seems working fine in IE 9 and above.

Here is a list of compatibility issues I found and fixed locally:

* missing `indexOf` and so on: ES 5 compatibility issue, can be fixed by [kriskowal/es5-shim](https://github.com/kriskowal/es5-shim/)
* error in jQuery: update jQuery to 1.11.x or [html5shiv.js](https://code.google.com/p/html5shiv/) seems fix it, mainly due to HTML 5 tags
* set title error: according to http://www.rachaelarnold.com/dev/archive/the-title-element-and-jquerys-text-function , using `document.title` instead of `$('title')` seems fix it 

I may come up with some pull requests shortly.

**Comment by Dynalon** [comment]
IE8 support will be completely dropped in the next release, sorry.
